# Sample .travis.yml for R projects from https://github.com/craigcitro/r-travis

language: r

env:
  - WARNINGS_ARE_ERRORS=false

r_github_packages:
  - jimhester/covr

matrix:
  include:
  - r: release
    after_success:
    - Rscript -e 'library(covr);coveralls();codecov()'
    before_cache: Rscript -e 'remotes::install_cran("pkgdown")'
    deploy:
      provider: script
      script: Rscript -e 'pkgdown::deploy_site_github()'
      skip_cleanup: true  
  
notifications:
  email:
    on_success: change
    on_failure: always
